#!/bin/bash 
##############################
# program name
#
# author: theNerd247 (nharvey@spsu.edu)
# version: 0.0.1
# 
# autodeployment user interface scsript
# see github.com/thernerd247/autodeploy for more info 
# 
# license: GPLv2 see LICENSE
##############################
install_files="post-receive autodeploy.conf"

function usage()
{
	echo -e "autodeploy_$version:
USAGE: autodeploy <Options>

Options: 
  --init initialize current directory to use autodeploy"
}

if [[ -z $1 ]]; then
	usage
	exit
fi

#check if in valid git directory
if [[ -d .git/hooks ]]; then
	GIT_DIR=".git"
elif [[ -d ./hooks ]]; then
	GIT_DIR="."
else
	echo "You must be in a git repo to install autodeploy"
	exit
fi

if [[ $1 == "--init" ]]; then
	for file in $install_files; do
		cp /usr/share/autodeploy/$file $GIT_DIR/hooks/
	done
fi
