#!/bin/bash
##############################
# program name
#
# author: theNerd247 (nharvey@spsu.edu)
# version: 0.0.3
# 
# Automatic deployment script for websites
# 
# license: GPLv2 see LICENSE
##############################

#default config variables 
branchfile=/etc/autodeploy/autodeploy
logfile=/var/log/autodeploy.log
webbase=/srv/http/
website_name="autodeploy_website"

#set the user mask to allow for creation of directories
umask g+w

# read in configuration for repo
. $GIT_DIR/hooks/autodeploy.conf

#debugging variable
TST=0

function debug 
{
	if [[ $TST == 1 ]]; then
		for cmd in "$@"; do 
			$cmd
		done
	fi
}

function userecho
{
	printf "======================================================================\n"
	printf "$1\n"
	printf "======================================================================\n"
}

function create
{
	userecho "A new deployment directory was found\nCreating deployment directory: $branch"
	
	#check of old dir exists
	if [[ -d ".$DEPLOYDIR" ]] ; then
		echo "hidden directory found....restoring"
		mv ".$DEPLOYDIR" $DEPLOYDIR
		exit
	fi
	
	#create repo, set pushed branch
	git clone --branch $branch $GIT_DIR $DEPLOYDIR

	if [[ ! -d $DEPLOYDIR ]] ; then
		echo "creating directory failed"
		return 1
	else
		echo "Creation success!"
	fi

	exit
}

function pull
{
	userecho "Updating deployment directory: $branch"
	cd $DEPLOYDIR
	
	echo "pulling in updates..."
	git pull origin $branch
}

function commit
{
	userecho "The deployment directory: $branch has been changed since the last push. Commiting the changes before I pull"
	cd $DEPLOYDIR
	git add -A
	git commit -m "pre deployment update for branch: $branch"
	git push origin $branch
	pull
}

function delete
{
	userecho "You've requested that this branch be deleted.\nRemoving from deploy directory list.\n(I'll keep the actual deployment directory incase you need it later.)" 
	mv $DEPLOYDIR "$webbase/.$branch"
	temp=$(grep -v -e "$branch" $branchfile) 
	echo -e "$temp" > $branchfile
	exit
}

#get updated branch
read old new refname

# get deploy branch
for branch in $branches; do
	debug "echo $branch"
	if [[ $refname == "refs/heads/$branch" ]]; then
		debug "echo DEBUG: deploy branch found: $branch"
		break
	fi
	branch=""
done

# check for no branch 
if [[ -z $branch ]] ; then
	userecho "No valid deployment directory found\n(Contact the server admin if one should be created)"
	exit
fi

#set the DEPLOYDIR
DEPLOYDIR=$webbase/${!branch}

#set the default deployment directory
if [[ -z DEPLOYDIR ]]; then
	DEPLOYDIR=$webbase/$website_name"$branch"
fi

if [[ ! -e refs/heads/$branch ]]; then
	CMD=delete
elif [[ ! -d $DEPLOYDIR ]] ; then
	CMD=create
else
	# get git status
	cd $DEPLOYDIR
	unset GIT_DIR
	status=$(git status --short)
	
	if [[ -z $status ]]; then
		CMD=pull
	else 		
		CMD=commit
	fi
fi

#operations to run when debugging
debug "echo DEBUG: status: $status"
debug	"echo DEBUG: refname: $refname DEPLOYDIR: $DEPLOYDIR"
debug	"echo DEBUG: [LOG UTC:$(date --utc +"%D %T")] $CMD: $branch"
debug "exit"

# log action
echo "[LOG UTC:$(date --utc +"%D %T"),$website_name] $CMD: $branch" >> $logfile

# run command based on action
$CMD
